# JVM 参数（赛扬 2 核环境调优）
org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8 -XX:+UseParallelGC
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=false
org.gradle.daemon=true

# Kotlin
kotlin.code.style=official
kotlin.incremental=true

# AndroidX
android.useAndroidX=true
android.nonTransitiveRClass=true
android.defaults.buildfeatures.buildconfig=false
